data:
  train_file: "data/precipitation_maxima.nc"
  ids_file: "data/ids.nc"
  output_dir: "data/synthetic"
model:
  noise_dim: 100
  batch_size: 50
  n_epochs: 30000
  decay: 0.9
  lambda_reg: 0.0
  learning_rate: 0.002 #0.0002 
training:
  use_gpu: true
  save_interval: 10 
  save_model: "generator.pt"
