data:
  train_file: "data/precipitation_maxima.nc"
  ids_file: "data/ids.csv"
  output_dir: "data/synthetic"
model:
  noise_dim: 100
  batch_size: 50
  n_epochs: 200
  learning_rate: 0.0002
  n_train: 50    
  d_train_it: 3  # Most effective 3:1 update ratio
  decay: 0.9     
training:
  use_gpu: true
  save_interval: 10 
  save_model: "generator.pt"

