data:
  ids_file: data/ids.csv
  output_dir: data/synthetic
  train_file: data/precipitation_maxima.nc
model:
  batch_size: 50
  d_train_it: 3
  decay: 0.9
  learning_rate: 0.0002
  n_epochs: 200
  n_train: 50
  noise_dim: 100
training:
  save_interval: 10
  save_model: generator.pt
  use_gpu: true
